### ISSUE TITLE
[Feature Request] include optional and user directories

### ISSUE THREAD

**Issue by kennyh7279** [crutchcorn/pyappsch#1]
Please add support for optional and user directories such as /opt , $HOME/.local/share/applications etc.

**Comment by crutchcorn** [comment]
Will do!

**Comment by crutchcorn** [comment]
Added ~/.local/share/applications as of 1b3ff448795eb565234cb651f23a99a8dc6f390e

**Comment by crutchcorn** [comment]
/opt will be much harder. I have to scan for binary files rather than .desktop files. This will require a bit more work but I will get to that when I can

**Comment by crutchcorn** [comment]
I retract my previous statement. /opt simply cannot be done. It's too complex to find the files. If they are meant to be launched, there should be a .desktop file in one of the two proper locations
